//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeShop.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавки.
        /// </summary>
        internal static string Adds {
            get {
                return ResourceManager.GetString("Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сметка.
        /// </summary>
        internal static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купи.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капучино.
        /// </summary>
        internal static string Cappucino {
            get {
                return ResourceManager.GetString("Cappucino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канела.
        /// </summary>
        internal static string Cinnamon {
            get {
                return ResourceManager.GetString("Cinnamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчистване.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафе.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафе магазин.
        /// </summary>
        internal static string CoffeeShop {
            get {
                return ResourceManager.GetString("CoffeeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безкофеиново Кафе.
        /// </summary>
        internal static string DecaffeinedCoffee {
            get {
                return ResourceManager.GetString("DecaffeinedCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еспресо.
        /// </summary>
        internal static string Espresso {
            get {
                return ResourceManager.GetString("Espresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език Български.
        /// </summary>
        internal static string LanguageBulgarian {
            get {
                return ResourceManager.GetString("LanguageBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мляко.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захар.
        /// </summary>
        internal static string Sugar {
            get {
                return ResourceManager.GetString("Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цяла сметка.
        /// </summary>
        internal static string Totalbill {
            get {
                return ResourceManager.GetString("Totalbill", resourceCulture);
            }
        }
    }
}
