//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeShop.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds.
        /// </summary>
        internal static string Adds {
            get {
                return ResourceManager.GetString("Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappucino.
        /// </summary>
        internal static string Cappucino {
            get {
                return ResourceManager.GetString("Cappucino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamon.
        /// </summary>
        internal static string Cinnamon {
            get {
                return ResourceManager.GetString("Cinnamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoffeeShop.
        /// </summary>
        internal static string CoffeeShop {
            get {
                return ResourceManager.GetString("CoffeeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecaffeinedCoffee.
        /// </summary>
        internal static string DecaffeinedCoffee {
            get {
                return ResourceManager.GetString("DecaffeinedCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espresso.
        /// </summary>
        internal static string Espresso {
            get {
                return ResourceManager.GetString("Espresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageBulgarian.
        /// </summary>
        internal static string LanguageBulgarian {
            get {
                return ResourceManager.GetString("LanguageBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar.
        /// </summary>
        internal static string Sugar {
            get {
                return ResourceManager.GetString("Sugar", resourceCulture);
            }
        }
    }
}
